# fly.toml app configuration file generated for orbia-sparkling-tree-7606 on 2025-05-23T17:57:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'orbia-sparkling-tree-7606'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
